### ISSUE TITLE
Root volume configuration and additional EBS volumes

### ISSUE THREAD

**Issue by jjhidalgar** [devopsmakers/terraform-aws-eks#2]
Launch templates should have the ability to configure the root volume and add additional EBS volumes of different sizes.

**Comment by js-timbirkett** [comment]
Thanks for the interest @jaimehrubiks - Launch templates _could_ support additional EBS volumes of different sizes but I'm not sure that they _should_ in the case of EKS worker nodes. I also notice that the upstream module: https://github.com/terraform-aws-modules/terraform-aws-eks doesn't support it at the moment.

Are there compelling reasons to support adding extra EBS volumes? Do managed node groups support EBS configuration? I'm not disagreeing or set against adding further EBS customisations but I'd like to understand the benefits and use cases more thoroughly 😄

**Comment by js-timbirkett** [comment]
Root volumes are customisable with this and the upstream module: 

Default values:
- https://github.com/devopsmakers/terraform-aws-eks/blob/master/modules/worker_groups/locals.tf
   (Search: root_)

Implemented:
- https://github.com/devopsmakers/terraform-aws-eks/blob/master/modules/worker_groups/worker_groups.tf#L175-L186

**Comment by jjhidalgar** [comment]
I added the pull request to the mainstream, which we could use here as well in the future if people find benefits on it.
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/800

A good use case is to create a set of workers for a Ceph cluster, which can then be used for dynamic storage provisioning. Ceph, in contrast to ebs, is faster to attach and can be used by instances/pods in any AZ. With this feature we can have separate partitions for os and storage, and even add more volumes and more types as time goes on.

I'm closing as I still don't know if it will be accepted on the mainstream
